-- ============================================
-- SETUP DATABASE DAIFUKU MOCHI (MySQL Version)
-- ============================================

-- Create Database
CREATE DATABASE IF NOT EXISTS daifuku_mochi;
USE daifuku_mochi;

-- Drop old tables if exist
DROP TABLE IF EXISTS DETAIL_PESANAN;
DROP TABLE IF EXISTS PESANAN;
DROP TABLE IF EXISTS KERANJANG;
DROP TABLE IF EXISTS PRODUK;
DROP TABLE IF EXISTS USERS;

-- Create USERS Table
CREATE TABLE USERS (
    ID_USER INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) DEFAULT 'pelanggan'
);

-- Create PRODUK Table
CREATE TABLE PRODUK (
    ID_PRODUK INT PRIMARY KEY AUTO_INCREMENT,
    NAMA_PRODUK VARCHAR(100) NOT NULL,
    HARGA INT NOT NULL,
    STOK INT DEFAULT 0,
    FOTO VARCHAR(255),
    DESKRIPSI VARCHAR(500)
);

-- Create KERANJANG Table
CREATE TABLE KERANJANG (
    ID_KERANJANG INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    ID_PRODUK INT NOT NULL,
    JUMLAH INT DEFAULT 1,
    FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUK) REFERENCES PRODUK(ID_PRODUK) ON DELETE CASCADE
);

-- Create PESANAN Table
CREATE TABLE PESANAN (
    ID_PESANAN INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    TANGGAL_PESANAN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL_HARGA INT NOT NULL,
    METODE_PEMBAYARAN VARCHAR(50),
    STATUS_PESANAN VARCHAR(30) DEFAULT 'Diproses',
    ALAMAT VARCHAR(500),
    NO_HP VARCHAR(15),
    FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE
);

-- Create DETAIL_PESANAN Table
CREATE TABLE DETAIL_PESANAN (
    ID_DETAIL INT PRIMARY KEY AUTO_INCREMENT,
    ID_PESANAN INT NOT NULL,
    ID_PRODUK INT NOT NULL,
    JUMLAH INT NOT NULL,
    HARGA_SATUAN INT NOT NULL,
    FOREIGN KEY (ID_PESANAN) REFERENCES PESANAN(ID_PESANAN) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUK) REFERENCES PRODUK(ID_PRODUK) ON DELETE CASCADE
);

-- Insert Initial Data
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) 
VALUES ('admin', 'admin123', 'admin');

INSERT INTO USERS (USERNAME, PASSWORD, ROLE) 
VALUES ('customer', 'customer123', 'pelanggan');

INSERT INTO PRODUK (NAMA_PRODUK, HARGA, STOK, FOTO, DESKRIPSI) 
VALUES ('Chocolate', 10000, 50, 'image/coklat.jpg', 'Mochi lembut isian coklat');

INSERT INTO PRODUK (NAMA_PRODUK, HARGA, STOK, FOTO, DESKRIPSI) 
VALUES ('Strawberry', 10000, 50, 'image/strowberry.jpg', 'Mochi segar strawberry');

INSERT INTO PRODUK (NAMA_PRODUK, HARGA, STOK, FOTO, DESKRIPSI) 
VALUES ('Matcha', 10000, 50, 'image/matcha.jpg', 'Mochi matcha Jepang');

INSERT INTO PRODUK (NAMA_PRODUK, HARGA, STOK, FOTO, DESKRIPSI) 
VALUES ('Blueberry', 10000, 50, 'image/anggur.jpg', 'Mochi rasa blueberry segar');

INSERT INTO PRODUK (NAMA_PRODUK, HARGA, STOK, FOTO, DESKRIPSI) 
VALUES ('Manggo Creamy', 10000, 50, 'image/manggo.jpg', 'Mochi mangga creamy');
