-- ============================================
-- SETUP DATABASE DAIFUKU MOCHI (SIMPLIFIED)
-- Jalankan script ini di SQL Developer (Tekan F5)
-- ============================================

-- Hapus tabel lama (Abaikan jika muncul error "table or view does not exist")
DROP TABLE DETAIL_PESANAN;
DROP TABLE PESANAN;
DROP TABLE KERANJANG;
DROP TABLE PRODUK;
DROP TABLE USERS;

-- Hapus sequence lama
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE PRODUK_SEQ;
DROP SEQUENCE KERANJANG_SEQ;
DROP SEQUENCE PESANAN_SEQ;
DROP SEQUENCE DETAIL_PESANAN_SEQ;

-- Buat Tabel USERS
CREATE TABLE USERS (
    ID_USER NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'pelanggan'
);
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

-- Buat Tabel PRODUK
CREATE TABLE PRODUK (
    ID_PRODUK NUMBER PRIMARY KEY,
    NAMA_PRODUK VARCHAR2(100) NOT NULL,
    HARGA NUMBER NOT NULL,
    STOK NUMBER DEFAULT 0,
    FOTO VARCHAR2(255),
    DESKRIPSI VARCHAR2(500)
);
CREATE SEQUENCE PRODUK_SEQ START WITH 1 INCREMENT BY 1;

-- Buat Tabel KERANJANG
CREATE TABLE KERANJANG (
    ID_KERANJANG NUMBER PRIMARY KEY,
    ID_USER NUMBER REFERENCES USERS(ID_USER),
    ID_PRODUK NUMBER REFERENCES PRODUK(ID_PRODUK),
    JUMLAH NUMBER DEFAULT 1
);
CREATE SEQUENCE KERANJANG_SEQ START WITH 1 INCREMENT BY 1;

-- Buat Tabel PESANAN
CREATE TABLE PESANAN (
    ID_PESANAN NUMBER PRIMARY KEY,
    ID_USER NUMBER REFERENCES USERS(ID_USER),
    TANGGAL_PESANAN DATE DEFAULT SYSDATE,
    TOTAL_HARGA NUMBER NOT NULL,
    METODE_PEMBAYARAN VARCHAR2(50),
    STATUS_PESANAN VARCHAR2(30) DEFAULT 'Diproses',
    ALAMAT VARCHAR2(500)
    NO_HP varchar(15)
);
CREATE SEQUENCE PESANAN_SEQ START WITH 1 INCREMENT BY 1;

-- Buat Tabel DETAIL_PESANAN
CREATE TABLE DETAIL_PESANAN (
    ID_DETAIL NUMBER PRIMARY KEY,
    ID_PESANAN NUMBER REFERENCES PESANAN(ID_PESANAN),
    ID_PRODUK NUMBER REFERENCES PRODUK(ID_PRODUK),
    JUMLAH NUMBER NOT NULL,
    HARGA_SATUAN NUMBER NOT NULL
);
CREATE SEQUENCE DETAIL_PESANAN_SEQ START WITH 1 INCREMENT BY 1;

-- Insert Data Awal
INSERT INTO USERS (ID_USER, USERNAME, PASSWORD, ROLE) VALUES (USERS_SEQ.NEXTVAL, 'admin', 'admin123', 'admin');

INSERT INTO PRODUK (ID_PRODUK, NAMA_PRODUK, HARGA, STOK, FOTO, DESKRIPSI)
VALUES (PRODUK_SEQ.NEXTVAL, 'Chocolate', 10000, 50, 'image/coklat.jpg', 'Mochi lembut isian coklat');

INSERT INTO PRODUK (ID_PRODUK, NAMA_PRODUK, HARGA, STOK, FOTO, DESKRIPSI)
VALUES (PRODUK_SEQ.NEXTVAL, 'Strawberry', 10000, 50, 'image/strowberry.jpg', 'Mochi segar strawberry');

INSERT INTO PRODUK (ID_PRODUK, NAMA_PRODUK, HARGA, STOK, FOTO, DESKRIPSI)
VALUES (PRODUK_SEQ.NEXTVAL, 'Matcha', 10000, 50, 'image/matcha.jpg', 'Mochi matcha Jepang');

COMMIT;
